version: '= 0'
conditions: v1
jobs:
  include:
  - name: ğŸ±
    sudo: false
    script: echo ğŸ‰
  - name: dup
    script: echo bar
    sudo: required
  - name: dup
    script: echo baz
    sudo: false
    if: ENV(FOO) = foo
    env:
    - FOO=foo